"""Decode the game's archived data files into readable text in analysis/data/.

* the SpriteKit scenes ``GameScene.sks``, ``Actions.sks`` and ``Snow.sks``: NSKeyedArchiver binary
  plists, read with plistlib, written as each archived object with its class and keys, references
  shown as ``#n`` (the object's index in ``$objects``) -> ``analysis/data/sks_<name>.txt``
* the compiled storyboards in ``game/Base.lproj``: their Info.plist, and each ``.nib``, which is
  Apple's NIBArchive format rather than a plist: a header, then tables of objects, keys, values and
  class names, with varints whose last byte has the high bit set -> ``analysis/data/nib_<storyboard>.txt``
* ``game/Info.plist`` -> ``analysis/data/info_plist.txt``
* the names in ``game/Assets.car``, the compiled asset catalogue, picked out as the printable runs that
  look like asset names -> ``analysis/data/assets_names.txt``.  The catalogue's own BOM format is not
  decoded; the port shows no images, so the names are all that is wanted from it.

Nothing here writes outside analysis/data.

    python tools/archive.py
"""
from __future__ import annotations

import os
import plistlib
import re
import struct

import macho

GAME = os.path.join(macho.ROOT, 'game')
OUT = os.path.join(macho.ROOT, 'analysis', 'data')


def show(value, limit: int = 200) -> str:
    if isinstance(value, plistlib.UID):
        return '#%d' % value.data
    if isinstance(value, bytes):
        text = value[:limit].hex(' ')
        return 'bytes[%d] %s%s' % (len(value), text, ' ...' if len(value) > limit else '')
    if isinstance(value, float):
        return repr(value)
    return repr(value)


# ---- NSKeyedArchiver plists (.sks) ----------------------------------------------------------------

def keyed_archive(path: str) -> str:
    with open(path, 'rb') as fh:
        plist = plistlib.load(fh)
    objects = plist.get('$objects', [])
    lines = ['%s: an NSKeyedArchiver archive (%s), %d objects' % (os.path.basename(path),
                                                                 plist.get('$archiver'), len(objects)),
             'Generated by tools/archive.py.  #n is object n of $objects; $null is #0.', '',
             '$top: ' + ', '.join('%s = %s' % (k, show(v)) for k, v in plist.get('$top', {}).items()), '']

    def class_of(obj):
        if isinstance(obj, dict) and '$class' in obj:
            cls = objects[obj['$class'].data]
            if isinstance(cls, dict):
                return cls.get('$classname', '?')
        return type(obj).__name__

    def inline(v):
        """A reference to a plain value or a string shows the value too: '#6 = 1.0'."""
        text = show(v)
        if isinstance(v, plistlib.UID) and 0 < v.data < len(objects):
            target = objects[v.data]
            if isinstance(target, (int, float, str, bool)) and target != '$null':
                text += ' = %r' % (target,)
            elif isinstance(target, dict) and '$class' in target:
                text += ' (%s)' % class_of(target)
        return text

    for i, obj in enumerate(objects):
        if isinstance(obj, dict) and '$classname' in obj:
            lines.append('#%d  class description %s %s' % (i, obj['$classname'], obj.get('$classes')))
            continue
        if isinstance(obj, dict):
            lines.append('#%d  %s' % (i, class_of(obj)))
            for k, v in obj.items():
                if k == '$class':
                    continue
                if isinstance(v, list):
                    lines.append('      %-28s [%s]' % (k, ', '.join(inline(e) for e in v)))
                else:
                    lines.append('      %-28s %s' % (k, inline(v)))
        else:
            lines.append('#%d  %s' % (i, show(obj)))
    return '\n'.join(lines) + '\n'


# ---- NIBArchive (.nib) ------------------------------------------------------------------------------

def _nib_varint(data: bytes, i: int):
    value = shift = 0
    while True:
        byte = data[i]
        i += 1
        value |= (byte & 0x7F) << shift
        shift += 7
        if byte & 0x80:
            return value, i


def nib_archive(path: str) -> str:
    data = open(path, 'rb').read()
    if not data.startswith(b'NIBArchive'):
        return '%s is not a NIBArchive\n' % os.path.basename(path)
    (_one, _version, n_objects, objects_off, n_keys, keys_off, n_values, values_off,
     n_classes, classes_off) = struct.unpack_from('<10I', data, 10)
    keys, i = [], keys_off
    for _ in range(n_keys):
        length, i = _nib_varint(data, i)
        keys.append(data[i:i + length].decode('utf-8', 'replace'))
        i += length
    classes, i = [], classes_off
    for _ in range(n_classes):
        length, i = _nib_varint(data, i)
        extras, i = _nib_varint(data, i)
        i += 4 * extras
        classes.append(data[i:i + length].rstrip(b'\0').decode('utf-8', 'replace'))
        i += length
    values, i = [], values_off
    for _ in range(n_values):
        key, i = _nib_varint(data, i)
        kind = data[i]
        i += 1
        if kind == 0:
            v = struct.unpack_from('<b', data, i)[0]; i += 1
        elif kind == 1:
            v = struct.unpack_from('<h', data, i)[0]; i += 2
        elif kind == 2:
            v = struct.unpack_from('<i', data, i)[0]; i += 4
        elif kind == 3:
            v = struct.unpack_from('<q', data, i)[0]; i += 8
        elif kind == 4:
            v = False
        elif kind == 5:
            v = True
        elif kind == 6:
            v = struct.unpack_from('<f', data, i)[0]; i += 4
        elif kind == 7:
            v = struct.unpack_from('<d', data, i)[0]; i += 8
        elif kind == 8:
            length, i = _nib_varint(data, i)
            raw = data[i:i + length]
            i += length
            try:
                text = raw.decode('utf-8')
                v = text if text.isprintable() or text == '' else raw
            except UnicodeDecodeError:
                v = raw
        elif kind == 9:
            v = None
        elif kind == 10:
            v = plistlib.UID(struct.unpack_from('<I', data, i)[0]); i += 4
        else:
            v = '<unknown value type %d>' % kind
        values.append((keys[key] if key < len(keys) else '?%d' % key, v))
    objects = []
    i = objects_off
    for _n in range(n_objects):
        cls, i = _nib_varint(data, i)
        first, i = _nib_varint(data, i)
        count, i = _nib_varint(data, i)
        objects.append((classes[cls] if cls < len(classes) else '?', values[first:first + count]))

    def inline(v):
        """A reference names its object's class, and a string's text: '#85 (NSString 'scoreLabel')'."""
        text = show(v)
        if isinstance(v, plistlib.UID) and v.data < len(objects):
            cls, vals = objects[v.data]
            words = [x for k, x in vals if k == 'NS.bytes' and isinstance(x, str)]
            text += ' (%s%s)' % (cls, ' %r' % words[0] if words else '')
        return text

    lines = ['%s: a NIBArchive, %d objects, %d keys, %d values, %d classes'
             % (os.path.basename(path), n_objects, n_keys, n_values, n_classes)]
    for n, (cls, vals) in enumerate(objects):
        lines.append('#%d  %s' % (n, cls))
        for key, v in vals:
            lines.append('      %-36s %s' % (key, inline(v)))
    return '\n'.join(lines) + '\n'


# ---- the rest ---------------------------------------------------------------------------------------

def plist_text(path: str) -> str:
    with open(path, 'rb') as fh:
        plist = plistlib.load(fh)

    def walk(value, indent):
        pad = '    ' * indent
        if isinstance(value, dict):
            out = []
            for k, v in value.items():
                if isinstance(v, (dict, list)):
                    out.append('%s%s:' % (pad, k))
                    out += walk(v, indent + 1)
                else:
                    out.append('%s%s: %s' % (pad, k, show(v)))
            return out
        if isinstance(value, list):
            out = []
            for v in value:
                if isinstance(v, (dict, list)):
                    out.append('%s-' % pad)
                    out += walk(v, indent + 1)
                else:
                    out.append('%s- %s' % (pad, show(v)))
            return out
        return ['%s%s' % (pad, show(value))]

    return '%s\n\n%s\n' % (os.path.relpath(path, macho.ROOT).replace(os.sep, '/'), '\n'.join(walk(plist, 0)))


def asset_names(path: str) -> str:
    data = open(path, 'rb').read()
    runs = re.findall(rb'[A-Za-z][A-Za-z0-9_\-. ]{2,60}', data)
    names = sorted({r.decode() for r in runs if re.fullmatch(r'[A-Za-z][A-Za-z0-9_\-.]{2,60}', r.decode())})
    return ('Printable names in %s (not a decode of the catalogue; every run of 3 or more name-like '
            'characters, so it includes some noise)\n\n%s\n'
            % (os.path.relpath(path, macho.ROOT).replace(os.sep, '/'), '\n'.join(names)))


def write(name: str, text: str) -> None:
    with open(os.path.join(OUT, name), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)


def main() -> int:
    os.makedirs(OUT, exist_ok=True)
    written = []
    for name in sorted(os.listdir(GAME)):
        if name.endswith('.sks'):
            out = 'sks_%s.txt' % name[:-4]
            write(out, keyed_archive(os.path.join(GAME, name)))
            written.append(out)
    base = os.path.join(GAME, 'Base.lproj')
    for board in sorted(os.listdir(base)):
        folder = os.path.join(base, board)
        if not os.path.isdir(folder):
            continue
        parts = []
        for name in sorted(os.listdir(folder)):
            path = os.path.join(folder, name)
            if name.endswith('.nib'):
                parts.append('=' * 100 + '\n' + nib_archive(path))
            elif name.endswith('.plist'):
                parts.append('=' * 100 + '\n' + plist_text(path))
        out = 'nib_%s.txt' % board.split('.')[0]
        write(out, 'The compiled storyboard %s, decoded by tools/archive.py\n\n' % board + '\n'.join(parts))
        written.append(out)
    write('info_plist.txt', plist_text(os.path.join(GAME, 'Info.plist')))
    written.append('info_plist.txt')
    car = os.path.join(GAME, 'Assets.car')
    if os.path.isfile(car):
        write('assets_names.txt', asset_names(car))
        written.append('assets_names.txt')
    print('wrote to analysis/data: ' + ', '.join(written))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
