"""Dump the game's classes: analysis/data/classes.json and a readable analysis/data/classes.txt.

For each of the nine classes in __objc_classlist: its superclass, its instance size, its instance
variables with their offsets (the offsets the Swift code reads its stored properties at), its properties,
its protocols, and every Objective-C method with the address of its implementation.  Then Swift 3's
reflection metadata: each Swift type's stored fields, by name and mangled type, in declaration order.

It also copies game/InsideTheCave to analysis/bin/InsideTheCave_arm64, so the analysis can be redone
from analysis/ alone.

    python tools/classes.py
"""
from __future__ import annotations

import json
import os
import shutil

import macho

OUT = os.path.join(macho.ROOT, 'analysis', 'data')
BIN = os.path.join(macho.ROOT, 'analysis', 'bin', 'InsideTheCave_arm64')
SOURCE = os.path.join(macho.ROOT, 'game', 'InsideTheCave')


def copy_binary() -> bool:
    """Copy the app's binary into analysis/bin, unless an identical copy is already there."""
    os.makedirs(os.path.dirname(BIN), exist_ok=True)
    if os.path.isfile(BIN) and open(BIN, 'rb').read() == open(SOURCE, 'rb').read():
        return False
    shutil.copyfile(SOURCE, BIN)
    return True


def as_json(m: macho.MachO) -> dict:
    return {
        'binary': os.path.relpath(m.path, macho.ROOT).replace(os.sep, '/'),
        'classes': [{
            'name': c.name, 'raw_name': c.raw_name, 'address': '0x%x' % c.address,
            'superclass': c.superclass, 'swift': c.swift, 'instance_size': c.instance_size,
            'protocols': c.protocols,
            'ivars': [{'offset': '0x%x' % off, 'name': name, 'type': typ, 'size': size}
                      for off, name, typ, size in c.ivars],
            'properties': [{'name': n, 'attributes': a} for n, a in c.properties],
            'methods': [{'name': meth.name(c.name), 'selector': meth.selector, 'types': meth.types,
                         'imp': '0x%x' % meth.imp} for meth in c.methods],
        } for c in m.classes],
        'swift_fields': [{'type': t, 'fields': [{'name': n, 'type': ft} for n, ft in fields]}
                         for t, fields in m.swift_fields()],
    }


def as_text(m: macho.MachO) -> str:
    lines = ['The classes of %s' % os.path.basename(m.path),
             'Generated by tools/classes.py.  Addresses are VM addresses; file offset = address - 0x100000000.',
             '']
    for c in m.classes:
        lines.append('=' * 100)
        lines.append('%s : %s    (%s, class at 0x%x, instance size %d%s)'
                     % (c.name, c.superclass, c.raw_name, c.address, c.instance_size,
                        ', Swift' if c.swift else ''))
        if c.protocols:
            lines.append('  protocols: ' + ', '.join(c.protocols))
        if c.ivars:
            lines.append('  instance variables (offset, name, size, type):')
            for off, name, typ, size in sorted(c.ivars):
                lines.append('    0x%-4x %-24s %3d  %s' % (off, name, size, typ))
        if c.properties:
            lines.append('  properties:')
            for name, attrs in c.properties:
                lines.append('    %-24s %s' % (name, attrs))
        if c.methods:
            lines.append('  methods (implementation, name, type encoding):')
            for meth in c.methods:
                lines.append('    0x%x  %-60s %s' % (meth.imp, meth.name(c.name), meth.types))
        lines.append('')
    lines.append('=' * 100)
    lines.append("Swift 3 reflection: each type's stored fields, in declaration order")
    lines.append('')
    for t, fields in m.swift_fields():
        lines.append('%s' % t)
        for n, ft in fields:
            lines.append('    %-24s %s' % (n, ft))
        lines.append('')
    return '\n'.join(lines) + '\n'


def main() -> int:
    copied = copy_binary()
    m = macho.load(SOURCE)
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, 'classes.json'), 'w', encoding='utf-8', newline='\n') as fh:
        json.dump(as_json(m), fh, indent=1)
        fh.write('\n')
    with open(os.path.join(OUT, 'classes.txt'), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(as_text(m))
    methods = sum(len(c.methods) for c in m.classes)
    print('%s analysis/bin/InsideTheCave_arm64; wrote analysis/data/classes.json and classes.txt: '
          '%d classes, %d methods, %d Swift types'
          % ('copied the binary to' if copied else 'already had', len(m.classes), methods,
             len(m.swift_fields())))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
