"""Write the whole of __text out as annotated listings, one file per class.

Every function goes into ``analysis/disasm/dz_<Class>.txt`` for the class whose name it carries
(``GameScene``, ``-[GameScene ...]``, ``GameScene.createMonster~closure1``, ``GameScene~shared2``,
``GameScene.vtable[4]``), and every function no class claims - Swift's own metadata accessors, witness
tables, trampolines and the helpers several classes share - into ``analysis/disasm/dz_other.txt``.
Within a file the functions are in address order.  Each opens with a header:

    //// GameScene.createMonster  0x10000caf8..0x10000d180  (thunk of -[GameScene createMonster])
    //// called by: -[GameScene createMonster]

and lists every instruction from its first byte to the next function's first, annotated by tools/dz.py.
tools/coverage.py reads these files back to prove nothing in __text was left out.

    python tools/listings.py
"""
from __future__ import annotations

import os

import dz
import macho
import names as naming

OUT = os.path.join(macho.ROOT, 'analysis', 'disasm')
OTHER = 'other'


def owner(name: str, classes: set) -> str:
    if name.startswith(('-[', '+[')):
        head = name[2:].split(' ')[0]
    else:
        head = name.split('~')[0].split('.')[0]
    return head if head in classes else OTHER


def main() -> int:
    d = dz.Disassembler()
    found, graph = naming.compute(d)
    d.names = {va: n for va, (n, _how) in found.items()}
    naming.write(found, graph, d)
    callers = graph.callers()
    classes = {c.name for c in d.m.classes}
    files: dict[str, list[str]] = {}
    for f in d.starts:
        name, how = found[f]
        begin, end = d.bounds(f)
        who = sorted(callers.get(f, ()))
        block = ['//// %s  0x%x..0x%x%s' % (name, begin, end, '  (%s)' % how if how else '')]
        if who:
            block.append('//// called by: ' + ', '.join(found[w][0] for w in who))
        block += [x.text() for x in d.function(f)]
        files.setdefault(owner(name, classes), []).append('\n'.join(block))
    os.makedirs(OUT, exist_ok=True)
    for old in os.listdir(OUT):
        if old.startswith('dz_') and old.endswith('.txt'):
            os.remove(os.path.join(OUT, old))
    for cls, blocks in sorted(files.items()):
        head = ['Inside The Cave: %s' % ('the functions no class claims' if cls == OTHER
                                         else 'the functions of ' + cls),
                'Generated by tools/listings.py from %s.  Addresses are VM addresses;'
                % os.path.relpath(d.m.path, macho.ROOT).replace(os.sep, '/'),
                'file offset = address - 0x100000000.  Annotations after ";" are what tools/dz.py could tell',
                'on the straight path into each instruction; the instructions themselves are complete.',
                '%d functions.' % len(blocks), '']
        with open(os.path.join(OUT, 'dz_%s.txt' % cls), 'w', encoding='utf-8', newline='\n') as fh:
            fh.write('\n'.join(head) + '\n' + '\n\n'.join(blocks) + '\n')
    print('wrote %d listings to analysis/disasm: %s'
          % (len(files), ', '.join('%s (%d)' % (k, len(v)) for k, v in sorted(files.items()))))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
