"""Every string in Inside The Cave's binary, with the functions that use it.

Writes analysis/data/strings.txt: the C strings (__cstring), the UTF-16 strings (__ustring, where text
with accents or other scripts is kept), the selector names (__objc_methname) and Swift's mangled type
references (__swift3_typeref), each at its address, followed by the functions whose code builds that
address.  A string no code builds may still be used: through a selector reference, a class's metadata,
or as part of a longer string.  The list says "no code loads it" rather than guess.

Swift 3 keeps a string literal as its bytes and a length, so the code may point into the middle of a
string; such a load is listed under the string it falls in, with its offset.

    python tools/strings.py
"""
from __future__ import annotations

import bisect
import os

import dz
import macho
import names as naming

OUT = os.path.join(macho.ROOT, 'analysis', 'data', 'strings.txt')
SECTIONS = (('__cstring', 'C strings'), ('__ustring', 'UTF-16 strings'),
            ('__objc_methname', 'selector names'), ('__swift3_typeref', 'Swift type references'))


def main() -> int:
    d = dz.Disassembler()
    found, _graph = naming.compute(d)
    d.names = {va: n for va, (n, _how) in found.items()}
    uses: dict[int, list[tuple[int, str]]] = {}
    for f in d.starts:
        for x in d.function(f):
            for va in x.addrs:
                uses.setdefault(va, []).append((x.address, found[f][0]))
    m = d.m
    lines = ['Every string in %s, with the functions that build its address'
             % os.path.relpath(m.path, macho.ROOT).replace(os.sep, '/'),
             'Generated by tools/strings.py.  "at" is where the instruction is; a load into the middle of a',
             'string is listed under that string with its offset.  Selector names are mostly used through',
             '__objc_selrefs, which the listings resolve, so few show code here.', '']
    totals = []
    for sectname, title in SECTIONS:
        entries = m.ustrings() if sectname == '__ustring' else m.cstrings(sectname)
        if not entries:
            continue
        addresses = [va for va, _s in entries]
        by_string: dict[int, list[str]] = {}
        for va, refs in uses.items():
            i = bisect.bisect_right(addresses, va) - 1
            if i < 0:
                continue
            start, text = entries[i]
            width = 2 if sectname == '__ustring' else 1
            if va >= start + (len(text) * width if sectname == '__ustring'
                              else len(text.encode('utf-8'))) + width:
                continue
            for at, fn in refs:
                offset = '' if va == start else ' +%d' % (va - start)
                by_string.setdefault(start, []).append('%s at 0x%x%s' % (fn, at, offset))
        lines.append('=' * 100)
        lines.append('%s (%s, %d)' % (title, sectname, len(entries)))
        lines.append('')
        used = 0
        for va, text in entries:
            lines.append('0x%x  %r' % (va, text))
            refs = by_string.get(va)
            if refs:
                used += 1
                for r in sorted(set(refs)):
                    lines.append('            used by %s' % r)
            elif sectname in ('__cstring', '__ustring'):
                lines.append('            no code loads it')
        lines.append('')
        totals.append('%d %s (%d loaded by code)' % (len(entries), title, used))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(lines) + '\n')
    print('wrote analysis/data/strings.txt: ' + ', '.join(totals))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
